# Generated by Django 4.2.7 on 2023-12-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0002_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
